# This is a basic workflow that is manually triggered

name: CI Manual Pipeline

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        java: [17]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
      with:
        path: main
    - name: Set up JDK ${{ matrix.java }}
      uses: actions/setup-java@v3
      with:
        distribution: 'oracle'
        java-version: ${{ matrix.java }}
    - name: Build with Maven
      working-directory: main
      run: mvn test
    - name: Publish Contract Test Report
      run: mvn specmatic:report
    - name: Upload Contract Test Report
      uses: actions/upload-artifact@v2
      with:
        name: contract-test-report
        path: target/specmatic-report.html
