# This is a basic workflow that is manually triggered

name: CI Manual Pipeline

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        java: [17]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
      with:
        path: main
    - name: Set up JDK ${{ matrix.java }}
      uses: actions/setup-java@v3
      with:
        distribution: 'oracle'
        java-version: ${{ matrix.java }}
    - name: Build with Maven
      working-directory: main
      run: mvn test
    - name: Generate report
      working-directory: main
      run: mvn jacoco:report
    - name: Publish report
      uses: mikepenz/action-junit-report@v2
      if: always()
      with:
        report_paths: 'target/site/jacoco/index.html'
