# This is a basic workflow that is manually triggered

name: CI Manual Pipeline

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        java: [17]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
      with:
        path: main
    - name: Set up JDK ${{ matrix.java }}
      uses: actions/setup-java@v3
      with:
        distribution: 'oracle'
        java-version: ${{ matrix.java }}
    - name: Build with Maven
      working-directory: main
      run: mvn test
    - name: Generate site report
      working-directory: main
      run: mvn site
    - name: Upload test report as artifact
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: test-report
        path: main/target/site  
    - name: Deploy test report to GitHub Pages
      if: success()
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: main/target/site
        destination_dir: test-report
    - name: Print site URL
      run: echo "Test Report published at https://<USERNAME>.github.io/<REPO>/test-report"
